package org.sindaryn.sanda;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.time.LocalDateTime;

public class StaticUtils {
    public static String toPascalCase(String string){
        return string.substring(0, 1).toUpperCase() + string.substring(1);
    }
    public static void writeToJavaFile(TypeElement entity,
                                       String packageName,
                                       TypeSpec.Builder builder,
                                       ProcessingEnvironment processingEnvironment,
                                       String templateType) {
        builder.addJavadoc(
                entity.getSimpleName().toString() +
                        " " + templateType + " generated by org.sindaryn.sanda @" +
                        LocalDateTime.now());
        final TypeSpec newClass = builder.build();
        final JavaFile javaFile = JavaFile.builder(packageName, newClass).build();

        try {
            javaFile.writeTo(System.out);
            javaFile.writeTo(processingEnvironment.getFiler());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
